export const emptyRecipe = {
  categories: [],
  cook_time: '',
  created: '',
  deleted: false,
  description: '',
  difficulty: '',
  directions: '',
  hash: '',
  image_url: null,
  ingredients: '',
  name: '',
  notes: '',
  nutritional_info: '',
  on_favorites: 0,
  photo: null,
  photo_hash: null,
  photo_url: '',
  prep_time: '',
  rating: 0,
  servings: '',
  scale: null,
  source: '',
  source_url: '',
  uid: '',
};
