export type RecipeFilter = {
  categories?: string[] | string;
  cook_time?: string;
  created?: string;
  description?: string;
  difficulty?: string;
  directions?: string;
  hash?: string;
  image_url?: string;
  in_trash?: boolean;
  ingredients?: string;
  is_pinned?: boolean;
  name?: string;
  notes?: string;
  nutritional_info?: string;
  on_favorites?: boolean;
  on_grocery_list?: boolean;
  photo?: string;
  photo_hash?: string;
  photo_large?: string;
  photo_url?: string;
  prep_time?: string;
  rating?: number;
  scale?: string;
  servings?: string;
  source?: string;
  source_url?: string;
  total_time?: string;
  uid?: string;
  limit?: number;
};
