export const emptyRecipe = {
	categories: [],
	cook_time: '',
	created: '',
	difficulty: '',
	hash: '',
	image_url: '',
	ingredients: '',
	name: '',
	notes: '',
	nutritional_info: '',
	on_favorites: false,
	photo_hash: '',
	photo: '',
	photo_url: '',
	prep_time: '',
	rating: 0,
	scale: 0,
	source: '',
	source_url: '',
	servings: '',
	uid: '',
};
